version: 2
jobs:
  build:
    working_directory: ~/best

    docker:
      - image: circleci/node:8.9.3-stretch-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
          - yarn-v3-{{ .Branch }}-{{ checksum "package.json" }}
          - yarn-v3-{{ .Branch }}-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - packages/*/node_modules
            - examples/*/node_modules
            - yarn.lock
          key: yarn-v3-{{ .Branch }}-{{ checksum "package.json" }}

  unit_test:
    working_directory: ~/best

    docker:
      - image: circleci/node:8.9.3-stretch-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
          - yarn-v3-{{ .Branch }}-{{ checksum "package.json" }}
          - yarn-v3-{{ .Branch }}-

      - run: yarn install

      - run:
          name: Unit Test
          command: yarn test

  performance_test_example:
    working_directory: ~/lwc

    docker:
      - image: circleci/node:8.9.3-stretch-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
          - yarn-v3-{{ .Branch }}-{{ checksum "package.json" }}
          - yarn-v3-{{ .Branch }}-

      - run: yarn install
      - run: yarn build
      - run:
          name: Performance Test - Example project
          command: yarn perf:example


workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: /\w+\/.*/

      - unit_test:
          requires:
            - build
          filters:
            branches:
              only: /\w+\/.*/

      - performance_test_example:
          requires:
            - build
          filters:
            branches:
              only: /\w+\/.*/
